# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '9.0'

target 'OitiReactNative' do
    # Comment the next line if you don't want to use dynamic frameworks
    use_frameworks!
    
    # Pods for sampleUsageLivenessSDK
    pod 'FaceCaptcha', '~> 4.0.1', :source => 'https://github.com/oititec/liveness-ios-specs.git'
  
  end
