# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '12.4'

target 'OitiReactNative' do
    # Comment the next line if you don't want to use dynamic frameworks
    use_frameworks!
    
    # Pods for sampleUsageLivenessSDK
    pod 'OILiveness2D', '1.2.2', :source => 'https://github.com/oititec/ios-artifactory-beta.git'
  
  end
